-- Disposable approximation of the inspected UMami schema; no live data.
create role anon;
create role authenticated;
create role service_role bypassrls;
create schema auth;
create schema storage;
revoke create on schema public from public;
grant usage on schema public, auth, storage to anon, authenticated, service_role;
create function auth.uid() returns uuid language sql stable as $$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid
$$;

create table public.users (
  id uuid primary key, email text not null unique, name text,
  avatar_url text, is_verified boolean default false, created_at timestamptz default now()
);
create table public.restaurants (
  id bigint generated by default as identity primary key, name text unique,
  rating_count integer default 0, rating_sum integer default 0
);
create table public.menu_items (
  id bigint generated always as identity primary key,
  restaurant_id bigint references public.restaurants, name text not null
);
create table public.reviews (
  id bigint generated by default as identity primary key,
  restaurant_id bigint references public.restaurants,
  user_id uuid references public.users default auth.uid(), rating real,
  comment text default '', photo_urls jsonb[], tags text[],
  helpful_count integer default 0, created_at timestamptz default now()
);
create table public.follows (
  follower_id uuid references public.users, following_id uuid references public.users,
  primary key (follower_id, following_id)
);
create table public.bookmarks (
  user_id uuid references public.users, restaurant_id bigint references public.restaurants,
  created_at timestamptz default now(), primary key (user_id, restaurant_id)
);
create table public.notifications (
  id uuid default gen_random_uuid() primary key, user_id uuid references public.users,
  type text not null, message text not null, is_read boolean default false,
  related_id uuid, created_at timestamptz default now()
);
create table public.review_helpful_votes (
  review_id integer references public.reviews, user_id uuid references public.users,
  created_at timestamptz default now(), primary key (review_id, user_id)
);
create table storage.objects (id uuid default gen_random_uuid(), bucket_id text, name text);
alter table storage.objects enable row level security;

grant all on all tables in schema public, storage to anon, authenticated, service_role;
grant all on all sequences in schema public to anon, authenticated, service_role;
-- Ensure a separately granted column privilege is revoked too.
grant update (is_verified) on public.users to authenticated;
create policy old_open_bookmarks on public.bookmarks for select using (true);
create policy old_any_owner_insert on public.bookmarks for insert to authenticated with check (true);
create policy "Allow authenticated uploads 1tsy3yu_0" on storage.objects
  for insert to authenticated with check (bucket_id = 'review-photos');
create policy "Allow public read 1tsy3yu_0" on storage.objects
  for select using (bucket_id = 'review-photos');
-- Deliberately broad policy proves the restrictive photo guard cannot be ORed away.
create policy unrelated_bucket_policy on storage.objects for all to anon, authenticated
  using (true) with check (true);

create function public.update_helpful_count() returns trigger language plpgsql as $$
begin
  if TG_OP = 'INSERT' then
    update reviews set helpful_count = helpful_count + 1 where id = NEW.review_id;
    return NEW;
  elsif TG_OP = 'DELETE' then
    update reviews set helpful_count = greatest(helpful_count - 1, 0) where id = OLD.review_id;
    return OLD;
  end if;
  return null;
end;
$$;
create function public.update_restaurant_rating_optimized() returns trigger language plpgsql as $$
begin
  if TG_OP = 'INSERT' then
    update restaurants set rating_count = rating_count + 1, rating_sum = rating_sum + NEW.rating
      where id = NEW.restaurant_id;
    return NEW;
  elsif TG_OP = 'DELETE' then
    update restaurants set rating_count = rating_count - 1, rating_sum = rating_sum - OLD.rating
      where id = OLD.restaurant_id;
    return OLD;
  elsif TG_OP = 'UPDATE' then
    if OLD.rating is distinct from NEW.rating or OLD.restaurant_id is distinct from NEW.restaurant_id then
      update restaurants set rating_count = rating_count - 1, rating_sum = rating_sum - OLD.rating
        where id = OLD.restaurant_id;
      update restaurants set rating_count = rating_count + 1, rating_sum = rating_sum + NEW.rating
        where id = NEW.restaurant_id;
    end if;
    return NEW;
  end if;
end;
$$;
create trigger trigger_update_helpful_count after insert or delete on public.review_helpful_votes
  for each row execute function public.update_helpful_count();
create trigger trigger_update_rating_optimized after insert or delete or update on public.reviews
  for each row execute function public.update_restaurant_rating_optimized();
